db: mongo
ui: layui

name: tahe_back
ip: 192.168.31.139
port: 9999

mongo:
  host: localhost
  db: tahe
  db_main: tahe

redis:
  host: 127.0.0.1 #192.168.0.111
  pass: #xSport#112233@Aa

# all=9, insert_update_del=3, update_del=2, del=1, none=0
audit_level: 9
log_err: 1
auto_role_query: 1

appid: wx0cfb01512fa70f08
appsecret: 2ac0138cfca822572cc252e32a2fc5c6

JWT_ISSUER: me
JWT_SECRET: zhiyue

# LLM Service Configuration
llm_api_endpoint: https://api.deepseek.com/v1/chat/completions
llm_model: deepseek-chat
llm_api_key: "sk-ba162e769e3b44a4bd9a42ab547e464f"  # 需要替换为实际的 API key