# Tahe DSL Generator - API Generator

require 'fileutils'
require_relative '../utils'

module Tahe
  module DSL
    class ApiGenerator
      include Utils::StringHelpers
      include Utils::PathHelpers
      include Utils::NamingHelpers

      attr_reader :model_data, :output_dir

      def initialize(model_data, output_dir = 'app/api')
        @model_data = model_data
        @output_dir = output_dir
      end

      # Generate API routes from model definition
      def self.generate_from_model(model_data, output_dir = 'app/api')
        generator = new(model_data, output_dir)
        generator.generate
      end

      # Generate API routes from .krmodel file
      def self.generate_from_file(krmodel_file, output_dir = 'app/api')
        require_relative '../parser/model_parser'
        model_data = ModelParser.parse_file(krmodel_file)
        generate_from_model(model_data, output_dir)
      end

      # Generate API routes from module definition
      def self.generate_from_module(module_data, output_dir = 'app/api')
        model_data = module_data['model']
        api_config = module_data['api']

        generator = new(model_data, output_dir)
        generator.generate(api_config)
      end

      # Generate all API files
      def generate(api_config = nil)
        FileUtils.mkdir_p(output_dir)

        # Generate routes file
        routes_file = generate_routes_file(api_config)

        # Generate controller file
        controller_file = generate_controller_file

        # Generate serializer file
        serializer_file = generate_serializer_file

        puts "Generated API files:"
        puts "  - #{routes_file}"
        puts "  - #{controller_file}"
        puts "  - #{serializer_file}"

        {
          routes: routes_file,
          controller: controller_file,
          serializer: serializer_file
        }
      end

      private

      def model_name
        @model_data['model']
      end

      def collection_name
        @model_data['collection'] || Utils::NamingHelpers.collection_name(model_name)
      end

      def base_path
        "/api/#{collection_name}"
      end

      # Generate routes file (Sinatra style)
      def generate_routes_file(api_config = nil)
        routes_content = generate_routes_content(api_config)
        routes_file = File.join(output_dir, "#{Utils::StringHelpers.underscore(collection_name)}_routes.rb")

        File.write(routes_file, routes_content)
        routes_file
      end

      def generate_routes_content(api_config)
        endpoints = api_config && api_config['endpoints'] ?
                    api_config['endpoints'] :
                    default_endpoints

        <<~RUBY
          # Generated API routes for #{model_name}
          # DO NOT EDIT THIS FILE MANUALLY

          require_relative '../controllers/#{Utils::StringHelpers.underscore(collection_name)}_controller'

          module API
            class #{model_name}Routes < Sinatra::Base
              # Base path: #{base_path}

              #{generate_authentication_middleware(api_config)}

              #{generate_rate_limiting_middleware(api_config)}

              #{generate_endpoint_routes(endpoints)}

              # Error handlers
              error JSON::ParserError do
                status 400
                json error: 'Invalid JSON in request body'
              end

              error ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound do
                status 404
                json error: 'Record not found'
              end

              error ActiveRecord::RecordInvalid do |e|
                status 422
                json error: 'Validation failed', details: e.record.errors.full_messages
              end

              error StandardError do |e|
                status 500
                json error: 'Internal server error', message: e.message
              end
            end
          end
        RUBY
      end

      def generate_authentication_middleware(api_config)
        return '' unless api_config && api_config['authentication']

        <<~RUBY
          # Authentication middleware
          before do
            authenticate_request!
          end
        RUBY
      end

      def generate_rate_limiting_middleware(api_config)
        return '' unless api_config && api_config['rate_limit'] && api_config['rate_limit']['enabled']

        config = api_config['rate_limit']
        <<~RUBY
          # Rate limiting: #{config['requests']} requests per #{config['period']}
          before do
            check_rate_limit!(#{config['requests']}, :#{config['period']})
          end
        RUBY
      end

      def generate_endpoint_routes(endpoints)
        endpoints.map do |endpoint|
          generate_single_route(endpoint)
        end.join("\n\n")
      end

      def generate_single_route(endpoint)
        method = endpoint['method'].downcase
        path = endpoint['path']
        action = endpoint['action']
        description = endpoint['description']
        strategy = endpoint['strategy']

        controller_action = "#{action}_#{Utils::StringHelpers.underscore(model_name)}"

        <<~RUBY.strip
          # #{description || action.capitalize}
          #{method} '#{path}' do
            controller = #{Utils::NamingHelpers.controller_name(model_name)}.new
            #{generate_strategy_call(strategy) if strategy}
            controller.#{action}(params)
          end
        RUBY
      end

      def generate_strategy_call(strategy)
        return '' unless strategy

        action = strategy['action']
        context = strategy['context']

        "# Strategy: #{action}/#{context}\n    "
      end

      def default_endpoints
        [
          {
            'method' => 'GET',
            'path' => '/',
            'action' => 'index',
            'description' => "List all #{collection_name}"
          },
          {
            'method' => 'POST',
            'path' => '/',
            'action' => 'create',
            'description' => "Create a new #{model_name}"
          },
          {
            'method' => 'GET',
            'path' => '/:id',
            'action' => 'show',
            'description' => "Get a single #{model_name}"
          },
          {
            'method' => 'PUT',
            'path' => '/:id',
            'action' => 'update',
            'description' => "Update a #{model_name}"
          },
          {
            'method' => 'DELETE',
            'path' => '/:id',
            'action' => 'destroy',
            'description' => "Delete a #{model_name}"
          },
          {
            'method' => 'GET',
            'path' => '/search',
            'action' => 'search',
            'description' => "Search #{collection_name}"
          }
        ]
      end

      # Generate controller file
      def generate_controller_file
        controller_content = generate_controller_content
        controller_file = File.join(output_dir, '../controllers', "#{Utils::StringHelpers.underscore(collection_name)}_controller.rb")

        FileUtils.mkdir_p(File.dirname(controller_file))
        File.write(controller_file, controller_content)
        controller_file
      end

      def generate_controller_content
        <<~RUBY
          # Generated controller for #{model_name}
          # DO NOT EDIT THIS FILE MANUALLY

          require_relative '../models/#{Utils::StringHelpers.underscore(model_name)}'
          require_relative '../serializers/#{Utils::StringHelpers.underscore(model_name)}_serializer'

          class #{Utils::NamingHelpers.controller_name(model_name)} < BaseController
            # GET #{base_path}
            def index(params)
              page = params[:page]&.to_i || 1
              page_size = params[:page_size]&.to_i || 20

              # Apply strategy: query/paginated
              records = #{model_name}.paginate(page: page, per_page: page_size)

              json(
                data: records.map { |r| #{model_name}Serializer.serialize(r) },
                meta: {
                  page: page,
                  page_size: page_size,
                  total: records.total_count
                }
              )
            end

            # POST #{base_path}
            def create(params)
              # Apply strategy: save/normal
              record = #{model_name}.new(permitted_params(params))

              if record.save
                json(
                  data: #{model_name}Serializer.serialize(record),
                  message: '#{model_name} created successfully'
                )
              else
                status 422
                json(
                  error: 'Validation failed',
                  details: record.errors.full_messages
                )
              end
            end

            # GET #{base_path}/:id
            def show(params)
              record = find_record(params[:id])

              json(
                data: #{model_name}Serializer.serialize(record)
              )
            end

            # PUT #{base_path}/:id
            def update(params)
              record = find_record(params[:id])

              # Apply strategy: save/normal
              if record.update(permitted_params(params))
                json(
                  data: #{model_name}Serializer.serialize(record),
                  message: '#{model_name} updated successfully'
                )
              else
                status 422
                json(
                  error: 'Validation failed',
                  details: record.errors.full_messages
                )
              end
            end

            # DELETE #{base_path}/:id
            def destroy(params)
              record = find_record(params[:id])

              # Apply strategy: delete/soft
              if record.destroy
                json(
                  message: '#{model_name} deleted successfully'
                )
              else
                status 422
                json(
                  error: 'Failed to delete #{model_name}'
                )
              end
            end

            # GET #{base_path}/search
            def search(params)
              keyword = params[:keyword]

              # Apply strategy: search/default
              records = #{model_name}.search(keyword)

              json(
                data: records.map { |r| #{model_name}Serializer.serialize(r) }
              )
            end

            private

            def find_record(id)
              #{model_name}.find(id)
            end

            def permitted_params(params)
              # TODO: Add strong parameters based on model fields
              params.slice(#{field_names_for_params})
            end
          end
        RUBY
      end

      def field_names_for_params
        fields = @model_data['fields'] || []
        field_names = fields.map { |f| ":#{f['name']}" }
        field_names.join(', ')
      end

      # Generate serializer file
      def generate_serializer_file
        serializer_content = generate_serializer_content
        serializer_file = File.join(output_dir, '../serializers', "#{Utils::StringHelpers.underscore(model_name)}_serializer.rb")

        FileUtils.mkdir_p(File.dirname(serializer_file))
        File.write(serializer_file, serializer_content)
        serializer_file
      end

      def generate_serializer_content
        <<~RUBY
          # Generated serializer for #{model_name}
          # DO NOT EDIT THIS FILE MANUALLY

          class #{model_name}Serializer
            def self.serialize(record)
              return nil unless record

              {
                #{generate_serializer_fields}
              }
            end

            def self.serialize_collection(records)
              records.map { |record| serialize(record) }
            end
          end
        RUBY
      end

      def generate_serializer_fields
        fields = @model_data['fields'] || []

        field_lines = fields.map do |field|
          field_name = field['name']
          field_type = field['type']

          case field_type
          when 'single_relation', 'multiple_relation'
            "#{field_name}: serialize_relation(record.#{field_name})"
          when 'date', 'datetime'
            "#{field_name}: record.#{field_name}&.iso8601"
          when 'amount'
            "#{field_name}: format_amount(record.#{field_name})"
          else
            "#{field_name}: record.#{field_name}"
          end
        end

        # Add timestamps if enabled
        if @model_data['timestamps']
          field_lines << 'created_at: record.created_at&.iso8601'
          field_lines << 'updated_at: record.updated_at&.iso8601'
        end

        # Add soft delete timestamp if enabled
        if @model_data['soft_delete']
          field_lines << 'deleted_at: record.deleted_at&.iso8601'
        end

        field_lines.map { |line| "        #{line}" }.join(",\n")
      end
    end
  end
end
