# Tahe DSL Generator - Model Generator

require 'json'
require 'fileutils'

module Tahe
  module DSL
    class ModelGenerator
      attr_reader :model_data, :output_dir

      def initialize(model_data, output_dir = 'app/models')
        @model_data = model_data
        @output_dir = output_dir
      end

      # 从.krmodel文件生成Ruby模型类
      def self.generate_from_file(krmodel_file, output_dir = 'app/models')
        model_data = JSON.parse(File.read(krmodel_file))
        generator = new(model_data, output_dir)
        generator.generate
      end

      # 生成模型类
      def generate
        FileUtils.mkdir_p(output_dir)

        model_file = File.join(output_dir, "#{model_name.underscore}.rb")
        File.write(model_file, generate_model_class)

        puts "Generated model: #{model_file}"
        model_file
      end

      private

      def model_name
        @model_data['model']
      end

      def collection_name
        @model_data['collection'] || model_name.underscore.pluralize
      end

      def generate_model_class
        <<~RUBY
          # Generated from #{model_name}.krmodel
          # DO NOT EDIT THIS FILE MANUALLY

          class #{model_name} < BaseModel
            # Collection name
            collection_name '#{collection_name}'

            #{generate_field_definitions}

            #{generate_indexes}

            #{generate_strategies}

            #{generate_hooks}

            #{generate_validations}
          end
        RUBY
      end

      def generate_field_definitions
        fields = @model_data['fields'] || []

        lines = fields.map do |field|
          options = build_field_options(field)
          "  field :#{field['name']}, :#{field['type']}#{options}"
        end

        lines.join("\n")
      end

      def build_field_options(field)
        options = []

        # Label
        options << "label: '#{field['label']}'" if field['label']

        # Required
        options << "required: true" if field['required']

        # Unique
        options << "unique: true" if field['unique']

        # Default
        options << "default: #{field['default'].inspect}" if field['default']

        # Validation
        if field['validation']
          validation_opts = field['validation'].map { |k, v| "#{k}: #{v.inspect}" }.join(', ')
          options << "validation: {#{validation_opts}}"
        end

        # Field-specific options
        if field['options']
          field_opts = field['options'].map { |k, v| "#{k}: #{v.inspect}" }.join(', ')
          options << "options: {#{field_opts}}"
        end

        # UI options
        if field['ui']
          ui_opts = field['ui'].map { |k, v| "#{k}: #{v.inspect}" }.join(', ')
          options << "ui: {#{ui_opts}}"
        end

        options.any? ? ", #{options.join(', ')}" : ""
      end

      def generate_indexes
        indexes = @model_data['indexes'] || []
        return "" if indexes.empty?

        lines = indexes.map do |index|
          fields = index['fields'].map { |f| "[#{f['field'].inspect}, #{f['order'] || 1}]" }.join(', ')
          options = []
          options << "unique: true" if index['unique']
          options << "sparse: true" if index['sparse']

          opts_str = options.any? ? ", #{options.join(', ')}" : ""
          "  index [#{fields}]#{opts_str}"
        end

        "\n  # Indexes\n" + lines.join("\n")
      end

      def generate_strategies
        strategies = @model_data['strategies'] || []
        return "" if strategies.empty?

        lines = strategies.map do |strategy|
          config = strategy['config'] ? ", config: #{strategy['config'].inspect}" : ""
          "  use_strategy :#{strategy['action']}, :#{strategy['context']}#{config}"
        end

        "\n  # Strategies\n" + lines.join("\n")
      end

      def generate_hooks
        hooks = @model_data['hooks'] || {}
        return "" if hooks.empty?

        lines = hooks.map do |hook_name, method_name|
          "  #{hook_name} :#{method_name}"
        end

        "\n  # Hooks\n" + lines.join("\n")
      end

      def generate_validations
        fields = @model_data['fields'] || []
        validations = []

        fields.each do |field|
          next unless field['validation']

          field_name = field['name']
          validation = field['validation']

          # Length validation
          if validation['min_length'] || validation['max_length']
            min = validation['min_length']
            max = validation['max_length']
            if min && max
              validations << "  validates :#{field_name}, length: {minimum: #{min}, maximum: #{max}}"
            elsif min
              validations << "  validates :#{field_name}, length: {minimum: #{min}}"
            elsif max
              validations << "  validates :#{field_name}, length: {maximum: #{max}}"
            end
          end

          # Numericality validation
          if validation['min'] || validation['max']
            opts = []
            opts << "greater_than_or_equal_to: #{validation['min']}" if validation['min']
            opts << "less_than_or_equal_to: #{validation['max']}" if validation['max']
            validations << "  validates :#{field_name}, numericality: {#{opts.join(', ')}}"
          end

          # Format validation
          if validation['pattern']
            validations << "  validates :#{field_name}, format: {with: /#{validation['pattern']}/}"
          end

          # Custom validation
          if validation['custom']
            validations << "  validate :#{validation['custom']}"
          end
        end

        return "" if validations.empty?

        "\n  # Validations\n" + validations.join("\n")
      end
    end
  end
end

# String helper methods
class String
  def underscore
    gsub(/::/, '/').
      gsub(/([A-Z]+)([A-Z][a-z])/,'\1_\2').
      gsub(/([a-z\d])([A-Z])/,'\1_\2').
      tr("-", "_").
      downcase
  end

  def pluralize
    # 简单的复数化，生产环境应使用ActiveSupport
    return self + 'es' if self.end_with?('s', 'x', 'z', 'ch', 'sh')
    return self[0..-2] + 'ies' if self.end_with?('y') && !%w[a e i o u].include?(self[-2])
    self + 's'
  end
end
