# Tahe DSL Generator - Page Generator

require 'fileutils'
require_relative '../utils'

module Tahe
  module DSL
    class PageGenerator
      include Utils::StringHelpers
      include Utils::PathHelpers
      include Utils::NamingHelpers

      attr_reader :page_data, :model_data, :output_dir

      def initialize(page_data, model_data = nil, output_dir = 'app/views')
        @page_data = page_data
        @model_data = model_data
        @output_dir = output_dir
      end

      # Generate page from parsed DSL
      def self.generate_from_dsl(page_data, model_data = nil, output_dir = 'app/views')
        generator = new(page_data, model_data, output_dir)
        generator.generate
      end

      # Generate page from .krdsl file
      def self.generate_from_file(krdsl_file, output_dir = 'app/views')
        require_relative '../parser/component_parser'
        require_relative '../parser/grid_parser'

        content = File.read(krdsl_file)

        # Detect DSL type
        if content.include?('grid ') && content.include?('item ')
          page_data = GridParser.parse(content)
          generator = new(page_data, nil, output_dir)
          generator.generate_grid_page
        else
          page_data = ComponentParser.parse(content)
          generator = new(page_data, nil, output_dir)
          generator.generate_component_page
        end
      end

      # Generate all page files
      def generate
        FileUtils.mkdir_p(output_dir)

        if @page_data['grid']
          generate_grid_page
        else
          generate_component_page
        end
      end

      # Generate component-based page
      def generate_component_page
        page_content = generate_component_page_content
        page_file = File.join(output_dir, "#{page_filename}.html.erb")

        File.write(page_file, page_content)
        puts "Generated page: #{page_file}"

        page_file
      end

      # Generate grid-based page
      def generate_grid_page
        page_content = generate_grid_page_content
        page_file = File.join(output_dir, "#{page_filename}.html.erb")

        File.write(page_file, page_content)
        puts "Generated page: #{page_file}"

        page_file
      end

      private

      def page_filename
        title = @page_data['page'] || @page_data['title'] || 'untitled'
        Utils::StringHelpers.underscore(title.gsub(/[^a-zA-Z0-9]/, '_'))
      end

      def page_title
        @page_data['page'] || @page_data['title'] || 'Untitled Page'
      end

      def layout_type
        @page_data['layout'] || 'admin'
      end

      def theme_type
        @page_data['theme'] || 'default'
      end

      # Generate component-based page content
      def generate_component_page_content
        <<~HTML
          <%# Generated from Component DSL %>
          <%# DO NOT EDIT THIS FILE MANUALLY %>

          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>#{page_title}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">

            <!-- Layui CSS -->
            <link rel="stylesheet" href="/assets/layui/css/layui.css">

            <!-- Custom CSS -->
            <link rel="stylesheet" href="/assets/css/app.css">
          </head>
          <body class="layout-#{layout_type} theme-#{theme_type}">

            <div class="layui-fluid">
              <div class="layui-row">
                <div class="layui-col-md12">
                  <div class="layui-card">
                    <div class="layui-card-header">
                      <h2>#{page_title}</h2>
                    </div>
                    <div class="layui-card-body">
                      #{generate_components}
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Layui JS -->
            <script src="/assets/layui/layui.js"></script>

            <!-- Page JS -->
            <script>
              layui.use(['table', 'form', 'layer'], function(){
                var table = layui.table;
                var form = layui.form;
                var layer = layui.layer;

                #{generate_component_scripts}
              });
            </script>
          </body>
          </html>
        HTML
      end

      def generate_components
        components = @page_data['components'] || []

        components.map do |component|
          generate_single_component(component)
        end.join("\n\n")
      end

      def generate_single_component(component)
        type = component['type']
        config = component['config'] || {}

        case type
        when 'crud_panel'
          generate_crud_panel(config)
        when 'search_table'
          generate_search_table(config)
        when 'tree_table_layout'
          generate_tree_table_layout(config)
        when 'form'
          generate_form(config)
        when 'table'
          generate_table(config)
        when 'toolbar'
          generate_toolbar(config)
        else
          "<!-- Unknown component type: #{type} -->"
        end
      end

      def generate_crud_panel(config)
        <<~HTML
          <!-- CRUD Panel -->
          <div class="crud-panel">
            <!-- Toolbar -->
            <div class="layui-btn-group">
              <button class="layui-btn layui-btn-sm" id="btn-add">
                <i class="layui-icon layui-icon-add-1"></i> 新增
              </button>
              <button class="layui-btn layui-btn-sm layui-btn-danger" id="btn-delete">
                <i class="layui-icon layui-icon-delete"></i> 删除
              </button>
            </div>

            <!-- Table -->
            <table class="layui-hide" id="crud-table" lay-filter="crud-table"></table>

            <!-- Row Tools Template -->
            <script type="text/html" id="rowTools">
              <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
              <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
            </script>
          </div>
        HTML
      end

      def generate_search_table(config)
        <<~HTML
          <!-- Search Table -->
          <div class="search-table">
            <!-- Search Form -->
            <form class="layui-form" lay-filter="search-form">
              <div class="layui-form-item">
                #{generate_search_fields(config['search_fields'])}
                <div class="layui-inline">
                  <button class="layui-btn" lay-submit lay-filter="search-submit">搜索</button>
                  <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                </div>
              </div>
            </form>

            <!-- Results Table -->
            <table class="layui-hide" id="search-table" lay-filter="search-table"></table>
          </div>
        HTML
      end

      def generate_search_fields(fields)
        return '' unless fields

        fields.map do |field|
          generate_search_field(field)
        end.join("\n")
      end

      def generate_search_field(field)
        type = field['type']
        name = field['name']
        label = field['label']
        placeholder = field['placeholder'] || ''

        case type
        when 'input'
          <<~HTML.strip
            <div class="layui-inline">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-inline">
                <input type="text" name="#{name}" placeholder="#{placeholder}" class="layui-input">
              </div>
            </div>
          HTML
        when 'select'
          <<~HTML.strip
            <div class="layui-inline">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-inline">
                <select name="#{name}">
                  <option value="">请选择</option>
                  #{generate_select_options(field['options'])}
                </select>
              </div>
            </div>
          HTML
        when 'date_range'
          <<~HTML.strip
            <div class="layui-inline">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-inline">
                <input type="text" name="#{name}_start" id="#{name}_start" placeholder="开始日期" class="layui-input">
              </div>
              <div class="layui-form-mid">-</div>
              <div class="layui-input-inline">
                <input type="text" name="#{name}_end" id="#{name}_end" placeholder="结束日期" class="layui-input">
              </div>
            </div>
          HTML
        else
          "<!-- Unknown search field type: #{type} -->"
        end
      end

      def generate_select_options(options)
        return '' unless options

        options.map do |opt|
          value = opt['value']
          text = opt['text']
          "<option value=\"#{value}\">#{text}</option>"
        end.join("\n")
      end

      def generate_tree_table_layout(config)
        <<~HTML
          <!-- Tree-Table Layout -->
          <div class="layui-row">
            <div class="layui-col-md4">
              <div class="layui-card">
                <div class="layui-card-header">#{config['tree_title'] || '树形结构'}</div>
                <div class="layui-card-body">
                  <ul id="tree" class="dtree" data-id="0"></ul>
                </div>
              </div>
            </div>
            <div class="layui-col-md8">
              <div class="layui-card">
                <div class="layui-card-header">#{config['table_title'] || '数据列表'}</div>
                <div class="layui-card-body">
                  <table class="layui-hide" id="tree-table" lay-filter="tree-table"></table>
                </div>
              </div>
            </div>
          </div>
        HTML
      end

      def generate_form(config)
        <<~HTML
          <!-- Form -->
          <form class="layui-form" lay-filter="main-form">
            #{generate_form_fields(config['fields'])}

            <div class="layui-form-item">
              <div class="layui-input-block">
                <button class="layui-btn" lay-submit lay-filter="form-submit">提交</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
              </div>
            </div>
          </form>
        HTML
      end

      def generate_form_fields(fields)
        return '' unless fields

        fields.map do |field|
          generate_form_field(field)
        end.join("\n")
      end

      def generate_form_field(field)
        type = field['type']
        name = field['name']
        label = field['label']
        required = field['required'] ? 'lay-verify="required"' : ''
        placeholder = field['placeholder'] || ''

        case type
        when 'input'
          input_type = field['input_type'] || 'text'
          <<~HTML.strip
            <div class="layui-form-item">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-block">
                <input type="#{input_type}" name="#{name}" placeholder="#{placeholder}" #{required} class="layui-input">
              </div>
            </div>
          HTML
        when 'textarea'
          rows = field['rows'] || 5
          <<~HTML.strip
            <div class="layui-form-item layui-form-text">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-block">
                <textarea name="#{name}" placeholder="#{placeholder}" #{required} class="layui-textarea" rows="#{rows}"></textarea>
              </div>
            </div>
          HTML
        when 'select'
          <<~HTML.strip
            <div class="layui-form-item">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-block">
                <select name="#{name}" #{required}>
                  <option value="">请选择</option>
                  #{generate_select_options(field['options'])}
                </select>
              </div>
            </div>
          HTML
        when 'switch'
          <<~HTML.strip
            <div class="layui-form-item">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-block">
                <input type="checkbox" name="#{name}" lay-skin="switch" lay-text="是|否">
              </div>
            </div>
          HTML
        when 'date'
          <<~HTML.strip
            <div class="layui-form-item">
              <label class="layui-form-label">#{label}</label>
              <div class="layui-input-block">
                <input type="text" name="#{name}" id="#{name}" placeholder="#{placeholder}" #{required} class="layui-input">
              </div>
            </div>
          HTML
        else
          "<!-- Unknown form field type: #{type} -->"
        end
      end

      def generate_table(config)
        <<~HTML
          <!-- Table -->
          <table class="layui-hide" id="data-table" lay-filter="data-table"></table>
        HTML
      end

      def generate_toolbar(config)
        <<~HTML
          <!-- Toolbar -->
          <div class="layui-btn-group">
            <button class="layui-btn layui-btn-sm">按钮1</button>
            <button class="layui-btn layui-btn-sm">按钮2</button>
          </div>
        HTML
      end

      def generate_component_scripts
        components = @page_data['components'] || []

        components.map do |component|
          generate_component_script(component)
        end.join("\n\n")
      end

      def generate_component_script(component)
        type = component['type']
        config = component['config'] || {}

        case type
        when 'crud_panel'
          generate_crud_panel_script(config)
        when 'search_table'
          generate_search_table_script(config)
        when 'tree_table_layout'
          generate_tree_table_script(config)
        else
          ''
        end
      end

      def generate_crud_panel_script(config)
        api_base = config['api_base'] || '/api/data'
        columns = config['columns'] || []

        <<~JS
          // CRUD Panel
          table.render({
            elem: '#crud-table',
            url: '#{api_base}',
            toolbar: '#toolbar',
            defaultToolbar: ['filter', 'exports', 'print'],
            cols: [#{generate_table_columns(columns)}],
            page: true
          });

          // Toolbar events
          $('#btn-add').on('click', function(){
            layer.open({
              type: 2,
              title: '新增',
              area: ['800px', '600px'],
              content: '#{api_base}/form'
            });
          });

          // Table tool events
          table.on('tool(crud-table)', function(obj){
            var data = obj.data;
            if(obj.event === 'edit'){
              layer.open({
                type: 2,
                title: '编辑',
                area: ['800px', '600px'],
                content: '#{api_base}/form?id=' + data.id
              });
            } else if(obj.event === 'del'){
              layer.confirm('确定删除吗？', function(index){
                $.ajax({
                  url: '#{api_base}/' + data.id,
                  type: 'DELETE',
                  success: function(){
                    obj.del();
                    layer.close(index);
                  }
                });
              });
            }
          });
        JS
      end

      def generate_search_table_script(config)
        table_source = config['table_source'] || '/api/data'
        columns = config['columns'] || []

        <<~JS
          // Search Table
          table.render({
            elem: '#search-table',
            url: '#{table_source}',
            cols: [#{generate_table_columns(columns)}],
            page: true
          });

          // Search form submit
          form.on('submit(search-submit)', function(data){
            table.reload('search-table', {
              where: data.field,
              page: {curr: 1}
            });
            return false;
          });
        JS
      end

      def generate_tree_table_script(config)
        tree_source = config['tree_source'] || '/api/tree'
        table_source = config['table_source'] || '/api/data'
        columns = config['columns'] || []

        <<~JS
          // Tree-Table Layout
          // TODO: Initialize tree component

          table.render({
            elem: '#tree-table',
            url: '#{table_source}',
            cols: [#{generate_table_columns(columns)}],
            page: true
          });
        JS
      end

      def generate_table_columns(columns)
        return '[]' unless columns

        cols = columns.map do |col|
          parts = []
          parts << "field: '#{col['field']}'" if col['field']
          parts << "title: '#{col['title']}'" if col['title']
          parts << "width: #{col['width']}" if col['width']
          parts << "sort: true" if col['sort']
          parts << "fixed: '#{col['fixed']}'" if col['fixed']
          parts << "type: '#{col['type']}'" if col['type']
          parts << "toolbar: '#{col['toolbar']}'" if col['toolbar']

          "{#{parts.join(', ')}}"
        end

        "[#{cols.join(', ')}]"
      end

      # Generate grid-based page content
      def generate_grid_page_content
        <<~HTML
          <%# Generated from Grid DSL %>
          <%# DO NOT EDIT THIS FILE MANUALLY %>

          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>#{page_title}</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">

            <!-- Layui CSS -->
            <link rel="stylesheet" href="/assets/layui/css/layui.css">

            <!-- GridStack CSS -->
            <link rel="stylesheet" href="/assets/gridstack/gridstack.min.css">

            <!-- Custom CSS -->
            <link rel="stylesheet" href="/assets/css/app.css">
          </head>
          <body>

            <div class="grid-stack">
              #{generate_grid_items}
            </div>

            <!-- Layui JS -->
            <script src="/assets/layui/layui.js"></script>

            <!-- GridStack JS -->
            <script src="/assets/gridstack/gridstack-all.js"></script>

            <!-- Page JS -->
            <script>
              // Initialize GridStack
              var grid = GridStack.init({
                cellHeight: #{@page_data['cell_height'] || 80},
                margin: #{@page_data['margin'] || 10},
                staticGrid: #{@page_data['static_grid'] || false},
                disableDrag: #{@page_data['disable_drag'] || false},
                disableResize: #{@page_data['disable_resize'] || false},
                animate: #{@page_data['animate'] || true}
              });

              #{generate_grid_scripts}
            </script>
          </body>
          </html>
        HTML
      end

      def generate_grid_items
        items = @page_data['items'] || []

        items.map do |item|
          generate_grid_item(item)
        end.join("\n")
      end

      def generate_grid_item(item)
        id = item['id']
        x = item['x']
        y = item['y']
        w = item['w']
        h = item['h']
        content = item['content']

        <<~HTML
          <div class="grid-stack-item" gs-id="#{id}" gs-x="#{x}" gs-y="#{y}" gs-w="#{w}" gs-h="#{h}">
            <div class="grid-stack-item-content">
              #{content}
            </div>
          </div>
        HTML
      end

      def generate_grid_scripts
        <<~JS
          layui.use(['form', 'table', 'layer'], function(){
            var form = layui.form;
            var table = layui.table;
            var layer = layui.layer;

            // Initialize form components
            form.render();

            // TODO: Add grid-specific scripts
          });
        JS
      end
    end
  end
end
